### ISSUE TITLE
Thread Error

### ISSUE THREAD

**Issue by harpreetsb** [hrkfdn/ncspot#192]
Using on Ubuntu.18.04
Usually after sleep, I get following error after one song

> `thread '<unnamed>' panicked at 'could not send no-op event to cursive: "SendError(..)"', src/events.rs:41:9
`

**Comment by morpheusthewhite** [comment]
![image](https://user-images.githubusercontent.com/36999173/83356186-962fe600-a364-11ea-9fa0-bc4655537176.png)

Me too here, after some time using ncspot (just minutes)

**Comment by rsvanda** [comment]
Hey there,

I get the same error and I guess it is network related issue, happens when I have the computer on an unstable wifi connection. 

When a request for a song (or its part) times out, the client does not recover and playback stops after all downloaded data is consumed. The gui part continues to work though as it probably does not know about failed playback client.

![Screenshot from 2020-06-01 09-37-19](https://user-images.githubusercontent.com/10668167/83387305-c7ec8f80-a3ec-11ea-83a3-21bc1accfcde.png)

I want to mention that I like `ncspot`, good work!

**Version**

* ncspot 0.1.3, installed via snap
* Ubuntu 20.04

**Comment by tommady** [comment]
I got the same issue, but run on macos,
<img width="1271" alt="Screen Shot 2020-06-09 at 21 14 08" src="https://user-images.githubusercontent.com/11532828/84152471-44d7d300-aa97-11ea-8d0f-cc7f11833590.png">
<img width="1281" alt="Screen Shot 2020-06-09 at 21 38 09" src="https://user-images.githubusercontent.com/11532828/84154334-8c5f5e80-aa99-11ea-8884-796a76b93f46.png">

but my backtrace says panic on this line
https://github.com/librespot-org/librespot/blob/6daa2acd0af7dfe70837592b33bfe9480783f852/playback/src/player.rs#L159

*version*
macos 10.15.4
ncspot 0.1.3 build with below command
```
cargo build --release --no-default-features --features rodio_backend,cursive/pancurses-backend
```

*steps*
1. pause the ncspot with shift p or not pause it goto sleep directly both panic on the same line.
2. put the mac into sleep, with or without the below setting (I tried both, the same result)
```
energy saver -> put hard disks to sleep when possible
```

3. wait a while, not too fast to wake the computer up,
define too fast: like pressing the sleep button then wake it up immediately, this will not panic and the ncspot will acting normally.

4. then finish the song remains, panic.

I am still trying to figure it out.

**Comment by theorangepotato** [comment]
I am also encountering this error. It is weird that people are getting different panic messages. My error looks like [these](https://github.com/hrkfdn/ncspot/issues/192#issuecomment-636487122) [two](https://github.com/hrkfdn/ncspot/issues/192#issuecomment-641308473), not the other two. I'd also like to point out that in both my log and @tommady's, there are two `[ERROR]` messages:

```
[2020-06-10][21:58:29] [librespot_playback::player] [ERROR] Unable to load audio item.
[2020-06-10][21:58:29] [librespot_core::session] [ERROR] Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
```

I wonder if the TCP connection is being reset once the system goes to sleep and librespot cannot handle that? My connection is not usually unstable, but I will always notice this after my computer sleeps. (I also remember it happening when my computer hasn't slept, but I have not yet reproduced this.)

On a related note, I have trouble copying the entire `stderr` message, as it seems to be caught in the TUI, and the terminal intercepts all clicks. Perhaps going forward you should pipe all normal `stderr` messages to actual `stderr`? I don't know if that would be a problematic change, but it would at least help with debugging.

### My System:
**operating system:** `Ubuntu 20.04`
**ncspot version:** `ncspot 0.1.3`
**installed via:** `cargo install ncspot --forced`

**Comment by tommady** [comment]
> I am also encountering this error. It is weird that people are getting different panic messages. My error looks like [these](https://github.com/hrkfdn/ncspot/issues/192#issuecomment-636487122) [two](https://github.com/hrkfdn/ncspot/issues/192#issuecomment-641308473), not the other two. I'd also like to point out that in both my log and @tommady's, there are two `[ERROR]` messages:
> 
> ```
> [2020-06-10][21:58:29] [librespot_playback::player] [ERROR] Unable to load audio item.
> [2020-06-10][21:58:29] [librespot_core::session] [ERROR] Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
> ```
> 
> I wonder if the TCP connection is being reset once the system goes to sleep and librespot cannot handle that? My connection is not usually unstable, but I will always notice this after my computer sleeps. ~(I also remember it happening when my computer hasn't slept, but I have not yet reproduced this.)~ This will also happen even when my computer has not slept! This theory may or may not still be correct, but it doesn't only correlate with my laptop sleeping.
> 
> On a related note, I have trouble copying the entire `stderr` message, as it seems to be caught in the TUI, and the terminal intercepts all clicks. Perhaps going forward you should pipe all normal `stderr` messages to actual `stderr`? I don't know if that would be a problematic change, but it would at least help with debugging.
> 
> ### My System:
> **operating system:** `Ubuntu 20.04`
> **ncspot version:** `ncspot 0.1.3`
> **installed via:** `cargo install ncspot --forced`

Hi @theorangepotato 
I found out the root cause of my reply and maybe can help you too.

the issue belongs to this: 
https://github.com/librespot-org/librespot/issues/134

and

https://github.com/librespot-org/librespot/pull/206
https://github.com/librespot-org/librespot/pull/427
those two MR fix that, but only when librespot running as a binary itself... not fix in the library...

so my solution is to 
1. build the librespot as binary and run it as a daemon
2. run a client who implements the Spotify connect feature to control it 

now the mac goes to sleep then wake up, the Spotify session will auto reconnected as well.

so for ncspot this repo, the ways to fix this issue are:
1. implement the reconnection logic itself. (OR)
2. wait for the librespot implement the reconnection logic into the library

hope this helped 🙇

**Comment by hrkfdn** [comment]
Hey there,

first of all thank you all for providing these detailed reports and logs, they are an immense assistance in tackling this.

I have committed an initial attempt at recreating a session when it has become invalid. As I can not reliably reproduce this issue, I'd love to hear if this improves things for you. If the issue persists, further log data would be helpful.

Cheers

**Comment by tommady** [comment]
Hi @hrkfdn 
first of all, thank you for spending your time for the greater good for us to use Spotify in CLI.

I logged the debug info
[debug.log](https://github.com/hrkfdn/ncspot/files/4776584/debug.log)

at [2020-06-14][22:20:12] [ncspot] [TRACE] event received: Paused
at [2020-06-14][22:26:50] [ncspot] [TRACE] event received: Playing

sleep about five minutes then wake the computer up on macOS,
then after the remained song end, the ncspot exit without anything words event the 
RUST_BACKTRACK=full env setted up.

hope this helped.

**Comment by hrkfdn** [comment]
Hey there, thanks for the report. So it seems that ncspot can at least detect that the session has died, which is a good first step, but recreating the session seems to fail. Unfortunately, backtrace output is logged to `stderr` and thus not in the normal debug log. You can log it by appending `2>stderr.log`. Would be awesome if you could attach a backtrace the next time it happens.

**Comment by tommady** [comment]
Hi @hrkfdn 
the only message I got from your suggestions setting is 
![image](https://user-images.githubusercontent.com/11532828/84600099-a211c100-aea9-11ea-84fc-51eb53ebcec3.png)

and this is the log of testing in this time
[debug.log](https://github.com/hrkfdn/ncspot/files/4776946/debug.log)

hope this helped 🙇

**Comment by hrkfdn** [comment]
Hey @tommady, yes it helps! Is this with `RUST_BACKTRACE=full` set, though? Anyway, based on this I have pushed a change which may help.

**Comment by tommady** [comment]
Hi @hrkfdn 
1. yes with *RUST_BACKTRACE=full*
2. it helps, now after sleep, the program is not panic but,
    a. finish the remained song, the next song displayed as expected but not playing.
    (not playing means the cursor and the time display of the song is not moving)
    b. the next song can be using the mouse to seek forward but still not playing.
    c. when I press the ENTER to try to play the song, the program panic

[stderr.log](https://github.com/hrkfdn/ncspot/files/4779919/stderr.log)
[debug.log](https://github.com/hrkfdn/ncspot/files/4779920/debug.log)

hope this helped 🙏

**Comment by hrkfdn** [comment]
Thanks again. I have pushed another fix and was able to reproduce it. In my case it successfully recreated the session. The UI was still a little off/out of sync, but after starting playback of another track things were fine. Some minor work remains, but it shouldn't be as fragile anymore.

Let men know if this fixes it for you. Make sure you pull the current state. I really appreciate all the feedback/reports.

**Comment by theorangepotato** [comment]
I can report that I experience the same behavior that you describe. It still stops the current queue, but doesn't crash the whole app anymore. Thanks for being so responsive on this issue!

**Comment by tommady** [comment]
coooool! now like @theorangepotato said.

it stops when the remained song finished,
but when I press ENTER to play the next song it will not panic and acting very beautifully normal!
this behavior is over what I expected!

thank you @hrkfdn !

**Comment by hrkfdn** [comment]
Glad it works! Then I'll close this issue.

**Comment by szaffarano** [comment]
Hi, I still have this issue.  It's pretty easy to reproduce it, just start playing a song, disconnect and reconnect wifi and when press `>` to play the next song, it won't play but it doesn't seem any error in the log:

```
[2021-06-24][11:20:32] [tokio_util::codec::framed_impl] [TRACE] framed transport flushed
[2021-06-24][11:20:40] [ncspot::spotify] [INFO] loading track: Track((Die Toten Hosen - Ballast der Republik (Some("61whykWjJe29sSbS1c5PX9"))))
[2021-06-24][11:20:40] [ncspot::spotify_worker] [INFO] player loading track: SpotifyId { id: 263116727897776758112800987915867240855, audio_type: Track }
[2021-06-24][11:20:40] [librespot_playback::player] [DEBUG] command=Load(SpotifyId { id: 263116727897776758112800987915867240855, audio_type: Track }, true, 0)
[2021-06-24][11:20:40] [librespot_playback::player] [TRACE] == Stopping sink ==
[2021-06-24][11:20:40] [tokio_util::codec::framed_impl] [TRACE] flushing framed transport
[2021-06-24][11:20:40] [tokio_util::codec::framed_impl] [TRACE] writing; remaining=83
[2021-06-24][11:20:40] [tokio_util::codec::framed_impl] [TRACE] framed transport flushed
```
I built `ncspot` locally, i.e. running `cargo install ncspot`
```
$ ncspot --version
ncspot 0.7.3

$ cargo --version
cargo 1.52.0 (69767412a 2021-04-21)
```
Thanks!

**Comment by jacksongoode** [comment]
@hrkfdn I think this issue still exists, I get thread hangups reliably when on a VPN with the latest version.
