### ISSUE TITLE
Mouse scroll doesn't work correctly

### ISSUE THREAD

**Issue by mhalano** [hrkfdn/ncspot#442]
I'm using the ncspot 0.4.0 (installed via Snap) and on the playlist I can scroll up using the mouse wheel, but I couldn't scroll down with the wheel.

**Comment by hrkfdn** [comment]
Hmm, can't reproduce this unfortunately. Did you try other terminals?

**Comment by mhalano** [comment]
I tried with Tilix and also Gnome Terminal, using Bash and Zsh. Same problem on the four possibilites.

**Comment by DannyJJK** [comment]
This happens to me using Alacritty 0.7.2 on macOS 11.2.2

**Comment by rbuch** [comment]
This was happening to me on Terminator on Ubuntu, as well.

Digging a bit, scrolling down with the mouse wheel produces a `cursive_core::event::MouseEvent::Hold(cursive_core::event::MouseButton::Left)` passed into `ListView::on_event` rather than a `cursive_core::event::MouseEvent::WheelDown`. This seems to be an issue stemming from cursive's pancurses backend not dealing with the legacy version of `NCURSES_MOUSE_VERSION` that Ubuntu uses, which encodes mouse wheel down events as what looks like a left mouse drag (see https://github.com/jeaye/ncurses-rs/issues/160 for more info). However, cursive's ncurses backend handles this situation properly (compare `parse_mouse_event` in the [ncurses version](https://github.com/gyscos/cursive/blob/cursive-v0.16.3/cursive/src/backends/curses/n.rs) and the [pancurses version](https://github.com/gyscos/cursive/blob/cursive-v0.16.3/cursive/src/backends/curses/pan.rs)), so compiling with `cursive/ncurses-backend` fixes this for me.

**Comment by rbuch** [comment]
This is now fixed in cursive as of https://github.com/gyscos/cursive/commit/3c7386dd50300c1ec7402d790f5ee5571bfff2ab.

**Comment by imlukedewitt** [comment]
Having the same issue on macOS 11.5.1, tested in iTerm2 and Terminal using ncspot 0.8.1

**Comment by mhalano** [comment]
@imlukedewitt I think the problem was fixed in the dependency, as pointed by @rbuch, but it wasn't pulled to ncspot yet.

**Comment by mhalano** [comment]
I'm waiting to version 0.8.2 be released in Snap Store to update and check if the scroll problem remains.

**Comment by hrkfdn** [comment]
Hey :), there is no stable release containing this fix yet which is why it wasn't pulled in

**Comment by DannyJJK** [comment]
@mhalano I still can't scroll downwards, and the scroll does jump over 2 items, as @Bettehem said as well. 
ncspot 0.9.0
alacritty 0.9.0 (fed349a)
macOS Monterey 12.0.1 (21A559)
(it was an issue on macOS Big Sur as well.)

Not sure how the mouse wheel scroll is being determined, I imagine the "jumping over 2 items" might be related to the scroll speed? It would probably be better if it scrolled like GNU Nano does without mouse mode on, where it seems to emulate up/down keys (which in this case, would also do what we want it to do)

**Comment by mhalano** [comment]
@DannyJJK I also got the two lines problem.
